name: ðŸš€ Deploy to AWS

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy (prod or test)'
        required: true
        default: 'production'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      - name: ðŸ§° Checkout repo
        uses: actions/checkout@v4

      - name: âš™ï¸ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm' # caches node_modules based on package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Create environment file
        run: |
          touch .env
          echo "NEXT_PUBLIC_BASE_URL=${{ vars.NEXT_PUBLIC_BASE_URL }}" >> .env
          echo "NEXT_PUBLIC_S3_CDN_HOST_NAME=${{ vars.NEXT_PUBLIC_S3_CDN_HOST_NAME }}" >> .env
          echo "REGION_AWS=${{ vars.REGION_AWS }}" >> .env
          echo "BLOG_POSTS_TABLE_NAME=${{ vars.BLOG_POSTS_TABLE_NAME }}" >> .env
          echo "S3_BUCKET_NAME=${{ vars.S3_BUCKET_NAME }}" >> .env
          echo "ADMIN_EMAIL=${{ secrets.ADMIN_EMAIL }}" >> .env
          echo "NEXTAUTH_URL=${{ vars.NEXTAUTH_URL }}" >> .env
          echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" >> .env
          echo "ACCESS_KEY_ID_AWS=${{ secrets.ACCESS_KEY_ID_AWS }}" >> .env
          echo "SECRET_ACCESS_KEY_AWS=${{ secrets.SECRET_ACCESS_KEY_AWS }}" >> .env
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
          echo "DEPLOY_ACCESS_KEY_ID_AWS=${{ secrets.DEPLOY_ACCESS_KEY_ID_AWS }}" >> .env
          echo "DEPLOY_SECRET_ACCESS_KEY_AWS=${{ secrets.DEPLOY_SECRET_ACCESS_KEY_AWS }}" >> .env
          echo "DEPLOY_S3_BUCKET_NAME=${{ vars.DEPLOY_S3_BUCKET_NAME }}" >> .env

      - name: Build app
        run: npm run build

      - name: Export static site
        run: npx next export

      - name: Install AWS CLI
        run: pip install awscli

      - name: Verify files to deploy
        run: ls -R ./out

      - name: ðŸ“¤ Deploy to S3
        run: |
          aws s3 sync ./out s3://${{ vars.DEPLOY_S3_BUCKET_NAME }} \
            --region ${{ vars.REGION_AWS }} \
            --delete \
            --cache-control "public, max-age=31536000, immutable"
        env:
          ACCESS_KEY_ID_AWS: ${{ secrets.DEPLOY_ACCESS_KEY_ID_AWS }}
          SECRET_ACCESS_KEY_AWS: ${{ secrets.DEPLOY_SECRET_ACCESS_KEY_AWS }}
          REGION_AWS: ${{ vars.REGION_AWS }}

      - name: Cleanup
        run: rm .env
