name: ðŸš€ Deploy to AWS

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy (prod or test)'
        required: true
        default: 'production'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.55.1-noble
      options: --ipc=host

    steps:
      - name: ðŸ§° Checkout repo
        uses: actions/checkout@v4

      - name: âš™ï¸ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm' # caches node_modules based on package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Create environment file
        run: |
          touch .env
          echo "NEXT_PUBLIC_BASE_URL=${{ vars.NEXT_PUBLIC_BASE_URL }}" >> .env
          echo "NEXT_PUBLIC_S3_CDN_HOST_NAME=${{ vars.NEXT_PUBLIC_S3_CDN_HOST_NAME }}" >> .env
          echo "AWS_REGION=${{ vars.AWS_REGION }}" >> .env
          echo "POSTS_TABLE=${{ vars.POSTS_TABLE }}" >> .env
          echo "S3_BUCKET_NAME=${{ vars.S3_BUCKET_NAME }}" >> .env
          echo "ADMIN_EMAIL=${{ secrets.ADMIN_EMAIL }}" >> .env
          echo "NEXTAUTH_URL=${{ vars.NEXTAUTH_URL }}" >> .env
          echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" >> .env
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
          echo "DEPLOY_AWS_ACCESS_KEY_ID=${{ secrets.DEPLOY_AWS_ACCESS_KEY_ID }}" >> .env
          echo "DEPLOY_AWS_SECRET_ACCESS_KEY=${{ secrets.DEPLOY_AWS_SECRET_ACCESS_KEY }}" >> .env
          echo "DEPLOY_S3_BUCKET_NAME=${{ vars.DEPLOY_S3_BUCKET_NAME }}" >> .env

      - name: Build app
        run: |
          echo "NEXT_PUBLIC_BASE_URL = $NEXT_PUBLIC_BASE_URL"
          echo "AWS_REGION = $AWS_REGION"
          npm run build

      - name: ðŸ“¤ Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --delete --cache-control "public, max-age=31536000, immutable"
        env:
          AWS_S3_BUCKET: ${{ vars.DEPLOY_S3_BUCKET_NAME }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOY_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOY_AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: './out'

      - name: Cleanup
        run: rm .env
