name: Playwright Tests

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
        default: test
      PLAYWRIGHT_PROJECT:
        required: false
        type: string
    secrets:
      ACCESS_KEY_ID_AWS:
        required: false
      SECRET_ACCESS_KEY_AWS:
        required: false
      NEXTAUTH_SECRET:
        required: false
      GOOGLE_CLIENT_ID:
        required: false
      GOOGLE_CLIENT_SECRET:
        required: false

jobs:
  test:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    container:
      image: mcr.microsoft.com/playwright:v1.56.1-noble
      options: --ipc=host

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - run: npm ci

      # --- If testing local app, download and start it ---
      - name: Download build
        if: ${{ inputs.ENVIRONMENT== 'test' }}
        uses: actions/download-artifact@v4
        with:
          name: next-build
          path: ${{ github.workspace }}/.next

      - name: Create environment file
        if: ${{ inputs.ENVIRONMENT == 'test' }}
        run: |
          echo "Creating .env file for test environment"
          touch .env
          echo "NEXT_PUBLIC_POINTED_AT_TEST=${{ vars.NEXT_PUBLIC_POINTED_AT_TEST }}" >> .env
          echo "NEXT_PUBLIC_BASE_URL=${{ vars.NEXT_PUBLIC_BASE_URL }}" >> .env
          echo "NEXT_PUBLIC_S3_CDN_HOST_NAME=${{ vars.NEXT_PUBLIC_S3_CDN_HOST_NAME }}" >> .env
          echo "REGION_AWS=${{ vars.REGION_AWS }}" >> .env
          echo "BLOG_POSTS_TABLE_NAME=${{ vars.BLOG_POSTS_TABLE_NAME }}" >> .env
          echo "QUESTIONS_TABLE_NAME=${{ vars.QUESTIONS_TABLE_NAME }}" >> .env
          echo "S3_BUCKET_NAME=${{ vars.S3_BUCKET_NAME }}" >> .env
          echo "ADMIN_EMAIL=${{ vars.ADMIN_EMAIL }}" >> .env
          echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" >> .env
          echo "ACCESS_KEY_ID_AWS=${{ secrets.ACCESS_KEY_ID_AWS }}" >> .env
          echo "SECRET_ACCESS_KEY_AWS=${{ secrets.SECRET_ACCESS_KEY_AWS }}" >> .env
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env

      # --- Install Playwright and run tests ---
      - name: Create environment file
        if: ${{ inputs.ENVIRONMENT == 'prod' }}
        run: |
          echo "Creating .env file for production environment"
          touch .env
          echo "NEXT_PUBLIC_BASE_URL=${{ vars.NEXT_PUBLIC_BASE_URL }}" >> .env

      - name: Run Playwright tests
        env:
          HOME: /root
        run: npx playwright test --project=${{ inputs.PLAYWRIGHT_PROJECT }}

      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: playwright-results
          path: |
            playwright-report/
          retention-days: 5
